apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: bella-skin-back
  namespace: bella-skin
spec:
  selector:
    matchLabels:
      app: bella-skin-back
  template:
    metadata:
      labels:
        app: bella-skin-back
    spec:
      containers:
        - name: bella-skin-back
          image: williambr2022/bella-skin-back
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DbUser
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: db_user
            - name: Database
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: database
            - name: DbPort
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: db_port
            - name: DbServer
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: db_server
            - name: KeyMD5
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: key_md5
            - name: Password
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: password
