apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- solucao-api.dep.yaml
- solucao-api.svc.yaml

namespace: solucao-laser

images:
- name: williambr2022/demo-agenda-back
  newName: williambr2022/demo-agenda-back
  newTag: 6e21676bb6cc765d3df7eb3c95ccd8edbaf448f6
- name: williambr2022/solucao-laser-back
  newName: williambr2022/solucao-laser-back
  newTag: 80bba840b9b662eee12178adc19907c17a93b9ca
