apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bella-skin-back.dep.yaml
- bella-skin-back.svc.yaml

namespace: bella-skin

images:
- name: williambr2022/bella-skin-back
  newName: williambr2022/bella-skin-back
  newTag: 9ae03d6cac279de307c13515297c98abef0525d2
