apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- solucao-api.dep.yaml
- solucao-api.svc.yaml

namespace: solucao-laser

images:
- name: solucao-api
  newName: williambr2022/solucao-api
  newTag: b50f8c578195c6ffb2bb67460a5b3bae89801376
