apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- solucao-api.dep.yaml
- solucao-api.svc.yaml

namespace: solucao-laser

images:
- name: solucao-api
  newName: williambr2022/solucao-api
  newTag: f43f3d4c0e7de72f7c7bc2e1e386c17974b8c1d0
