apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bella-skin-back.dep.yaml
- bella-skin-back.svc.yaml

namespace: bella-skin

images:
- name: bella-skin-back
  newName: williambr2022/bella-skin-back
  newTag: 1f16eb761029293a767b997cf3ef0d4b13063c0e
