apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bella-skin-back.dep.yaml
- bella-skin-back.svc.yaml

namespace: bella-skin

images:
- name: williambr2022/bella-skin-back
  newName: williambr2022/bella-skin-back
  newTag: 9216365b175cdef2f9dc453bdcb3bb2924e00520
