apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: solucao-api
spec:
  selector:
    matchLabels:
      app: solucao-api
  template:
    metadata:
      labels:
        app: solucao-api
    spec:
      containers:
        - name: solucao-api
          image: solucao-api
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DbUser
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: db_user
            - name: Database
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: database
            - name: DbPort
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: db_port
            - name: DbServer
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: db_server
            - name: Password
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
