name: CD production

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: build image and push to docker hub
      uses: docker/build-push-action@v1.1.0
      with:
        username: williambr2022
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: williambr2022/solucao-api
        tags: ${{ github.sha }}, latest
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build   
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: kustomize
        uses: imranismail/setup-kustomize@v2

      - name: update k8s
        run: |
          cd Kubernetes
          kustomize edit set image solucao-api=williambr2022/solucao-api:${{ github.sha }}
          cat kustomization.yaml
      - name: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -d $GITHUB_REF_NAME
          git tag $GITHUB_REF_NAME
          git commit -am "change image tag"
      - name: push
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
